# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.2.0
    - uses: actions/checkout@v2.2.0
      with:
        repository: apache/shardingsphere-elasticjob-ui
        ref: 'master'
        # path: 'elasticjob-ui'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        ls -l
        cd elasticjob-ui
        ls -l
        # mvn clean package -Prelease --file pom.xml
        ls -l shardingsphere-elasticjob-ui-distribution/
        ls -l shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-lite-ui-bin-distribution/
        ls -l shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-lite-ui-bin-distribution/target/
        cp ./shardingsphere-elasticjob-ui-distribution/*/target/*.tar.gz build/
